### ISSUE TITLE
post update 更新问题

### ISSUE THREAD

**Issue by shixiaocaia** [GoSimplicity/LinkMe#177]
最近在看佬的项目，看到 post 那边，帖子做了缓存，在 post 更新时会同步删除缓存，保持一致性。

我在想实际中是怎么做的，比如小红书的帖子如果被更新了，如何让用户第一时间感知到更新。如果过期时间设置的再短一些，依赖过期时间，短期内不一致性，但是减少了删除缓存操作加载也更快，是否会更好

**Comment by GoSimplicity** [comment]
> 最近在佬的项目，看到帖子那边，帖子里的帖子里更新了缓存，结婚了。
> 
> 我在想办法让它运行，比如小红书，如果被更新，如何让用户第一时间收到信息。如果过期了，再设置一些过期时间，但是不连续，但是删除缓存操作也会更快捷，最好能删除一些缓存，这样会比较好。

我们后期对post缓存改动的想法为对类似首页帖子列表这样比较重要的数据采取主动失效的策略保证数据一致性，对于其他不太重要的数据设置较短的过期时间

**Comment by shixiaocaia** [comment]
> > 最近在佬的项目，看到帖子那边，帖子里的帖子里更新了缓存，结婚了。
> > 我在想办法让它运行，比如小红书，如果被更新，如何让用户第一时间收到信息。如果过期了，再设置一些过期时间，但是不连续，但是删除缓存操作也会更快捷，最好能删除一些缓存，这样会比较好。
> 
> 我们后期对post缓存改动的想法为对类似首页帖子列表这样比较重要的数据采取主动失效的策略保证数据一致性，对于其他不太重要的数据设置较短的过期时间

上述打字好像快了，有点混乱。
我猜测可能是小红书那些，对热门数据可能既设置较长过期时间保证更快获取，更新时同步删除或者是更新，保证一致性，可能就像你说的对帖子打了便签“热门”，“首页”的帖子保证一致性，冷数据就依赖过期时间了。

另外想问下佬，有没有群之类的交流学习

**Comment by GoSimplicity** [comment]
> > > 最近在佬的项目，看到帖子那边，帖子里的帖子里更新了缓存，结婚了。
> > > 我在想办法让它运行，比如小红书，如果被更新，如何让用户第一时间收到信息。如果过期了，再设置一些过期时间，但是不连续，但是删除缓存操作也会更快捷，最好能删除一些缓存，这样会比较好。
> > 
> > 
> > 我们后期对post缓存改动的想法为对类似首页帖子列表这样比较重要的数据采取主动失效的策略保证数据一致性，对于其他不太重要的数据设置较短的过期时间
> 
> 上述打字好像快了，有点混乱。 我猜测可能是小红书那些，对热门数据可能既设置较长过期时间保证更快获取，更新时同步删除或者是更新，保证一致性，可能就像你说的对帖子打了便签“热门”，“首页”的帖子保证一致性，冷数据就依赖过期时间了。
> 
> 另外想问下佬，有没有群之类的交流学习

![Uploading WechatIMG228.jpg…]()

**Comment by GoSimplicity** [comment]
> > > 最近在佬的项目，看到帖子那边，帖子里的帖子里更新了缓存，结婚了。
> > > 我在想办法让它运行，比如小红书，如果被更新，如何让用户第一时间收到信息。如果过期了，再设置一些过期时间，但是不连续，但是删除缓存操作也会更快捷，最好能删除一些缓存，这样会比较好。
> > 
> > 
> > 我们后期对post缓存改动的想法为对类似首页帖子列表这样比较重要的数据采取主动失效的策略保证数据一致性，对于其他不太重要的数据设置较短的过期时间
> 
> 上述打字好像快了，有点混乱。 我猜测可能是小红书那些，对热门数据可能既设置较长过期时间保证更快获取，更新时同步删除或者是更新，保证一致性，可能就像你说的对帖子打了便签“热门”，“首页”的帖子保证一致性，冷数据就依赖过期时间了。
> 
> 另外想问下佬，有没有群之类的交流学习

加我v拉你：GoSimplicity
