### ISSUE TITLE
每次提交代码的时候能别传二进制文件吗？

### ISSUE THREAD

**Issue by wangzhensi** [GoSimplicity/LinkMe#219]

**Comment by GoSimplicity** [comment]
可以 我忽略掉吧

---- 回复的原邮件 ----
| 发件人 | Lil ***@***.***> |
| 发送日期 | 2024年08月16日 17:51 |
| 收件人 | GoSimplicity/LinkMe ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [GoSimplicity/LinkMe] 每次提交代码的时候能别传二进制文件吗？ (Issue #219) |

**Comment by GoSimplicity** [comment]
> _No description provided._

我原先就忽略掉了呀 你是在哪里看到的？

**Comment by wangzhensi** [comment]
tmp文件夹里面有一个main文件，我刚才看了一下，这个项目大小已经1个G了。估计是.git里面的二进制文件太多了

**Comment by wangzhensi** [comment]
每次pull代码都得等半天

**Comment by GoSimplicity** [comment]
> 每次pull代码都得等半天

air启动项目生成的...我还真没发现  感谢提出的建议

**Comment by GoSimplicity** [comment]
> 每次pull代码都得等半天

问题已解决 重新clone项目即可

**Comment by GoSimplicity** [comment]
已解决

**Comment by GoSimplicity** [comment]
1
