### ISSUE TITLE
语雀 LinkMe项目启动文档 被禁止加入了吗？

### ISSUE THREAD

**Issue by lv123123long** [GoSimplicity/LinkMe#243]
点击申请加入文档协作，浏览器无反应。通过F12抓取接口，接口也无反应。无法发送请求。该项目是否被禁止加入

**Comment by GoSimplicity** [comment]
> 点击申请加入文档协作，浏览器无反应。通过F12抓取接口，接口也无反应。无法发送请求。该项目是否被禁止加入

你可以看一下doc目录下 有.md的启动文档

**Comment by GoSimplicity** [comment]
解决
